// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/docs","parentId":"@@/global-layout","id":"2"},"3":{"path":"/chat","parentId":"@@/global-layout","id":"3"},"4":{"path":"/login","parentId":"@@/global-layout","id":"4"},"5":{"path":"/register","parentId":"@@/global-layout","id":"5"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__docs" */'@/pages/docs.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Chat__index" */'@/pages/Chat/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Register__index" */'@/pages/Register/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/documents/blockchain/Coinvisor-feat-fe/Coinvisor-feat-fe/frontend/src/layouts/index.tsx')),
},
  };
}
